### ISSUE TITLE
Add LICENSE?

### ISSUE THREAD

**Issue by GiovanniKl** [CEITECmagnonics/SpinWaveToolkit#10]
Do we want to add some license?

I'd suggest MIT license, which is quite standard from my experience. It ensures that we are not liable for any malfunction/damage done by using our package and we do not provide any warranty. The users are usually requested to cite the authors of this repository and the copyright notice.

More about licenses at [choosealicense.com](https://choosealicense.com/) (by GitHub), or [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository).

Other examples:
- Magpylib uses a BSD 2-Clause "Simplified" License (their [license](https://github.com/magpylib/magpylib/blob/main/LICENSE))
- TetraX uses a GNU license (their [license](https://codebase.helmholtz.cloud/micromagnetic-modeling/tetrax/-/blob/main/LICENSE?ref_type=heads))

**Comment by OndrejW** [comment]
I agree. There is no problem from my side. Maybe @michalu1 @michalurb  can comment on this (as he is the most experience with this)?

**Comment by michalurb** [comment]
I don't have much experience with this. But I like MIT license as it is short and understandable :-).

**Comment by GiovanniKl** [comment]
Ok, I have added a MIT license to the `SWT_reformatted` branch. I plan to do a pull request this evening (if everything goes well with other stuff).
