### ISSUE TITLE
Complete Tacchi model in SWT

### ISSUE THREAD

**Issue by GiovanniKl** [CEITECmagnonics/SpinWaveToolkit#5]
The Tacchi model has severe underdocumentation so far. It would be best if someone (probably Ondra) could comment or directly add more comments to the Tacchi model functions.

I don't quite understand why there are always only certain quantization numbers. Could this be further perfected or this model be replaced by some other?

**Comment by GiovanniKl** [comment]
Now I noticed that in some version of SWT the calculation of `DispersionCharacteristic.wU` (circular frequency of magnetocrystalline **OOP!** anisotropy) was changed from Material's surface anistropy attribute `Ku` to `Ku` supplied in the `__init__()` constructor function. The Material attribute `Ku` then is no longer used.

Also in the Material class, the `Ku` was not specified before to be surface anisotropy, but I deduced from its usage long time ago. In the SWT_reformatted branch this is commented, but now I see that maybe quite obsolete. It would be good to decide how to handle the `Material.Ku` (delete/implement back in Tacchi) and mention in the Tacchi model description the original paper and that the used `Ku` is **surface anisotropy constant**.

I think the original paper is this: [https://doi.org/10.1103/PhysRevB.100.104406](https://doi.org/10.1103/PhysRevB.100.104406)
Please, correct me if I'm wrong.

**Comment by OndrejW** [comment]
The situation is bit more complicated (even bigger mess than you think :D ) The wU in Tacchi is indeed OOP anisotropy but the second Ku is IP anisotropy for SAFs. I will try to fix it.

**Comment by OndrejW** [comment]
Documentation done, plus I have added an example of use (it may be redone to Jupyter later)
