### ISSUE TITLE
Correct SAF calculations in SWT?

### ISSUE THREAD

**Issue by GiovanniKl** [CEITECmagnonics/SpinWaveToolkit#6]
The calculation of SAF dispersions and free energies do no take into account the possibility to couple two different materials. The model now assumes they have the same gamma and alpha. Does this make sense when they can have different Ms, Ku, and Aex?

**Comment by OndrejW** [comment]
Alpha does not directly change anything in dispersion relation calculation (only in lifetime, but it does not seems very reliable in SAFs). The two different gammas significantly complicate formulation of the matrix of the two coupled LL equations and thus usually only "effective gamma" is used in the literature.

**Comment by OndrejW** [comment]
I propose to close this issue and for now stick to the one effective Gamma and alpha. What do you think @GiovanniKl ?

**Comment by GiovanniKl** [comment]
Okay. I see no problem there (if it will be mentioned in the documentation and the docstrings :D).

**Comment by GiovanniKl** [comment]
Closing the issue then.
