### ISSUE TITLE
Add .gitignore for apropriate files

### ISSUE THREAD

**Issue by GiovanniKl** [CEITECmagnonics/SpinWaveToolkit#9]
The .gitignore file might help unclutter this repository of redundant and useless files.

I suggest adding:

```.gitignore
# Byte-compiled
__pycache__/


# Jupyter Notebook
.ipynb_checkpoints

# Environments
.env
.venv
env/
venv/
ENV/
env.bak/
venv.bak/
.vscode/
```
And deleting all already existing files from the repository (they can stay at your local clone, but will no longer be synchronized when committing).

Not all listed things are present, but might be accidentally committed in the future. This list was inspired by [this](https://github.com/executablebooks/MyST-Parser/blob/master/.gitignore). If you have any suggestions, please comment.

**Comment by OndrejW** [comment]
Perfect! Just add the gitignore and close the issue.

**Comment by GiovanniKl** [comment]
I cleaned the repo of useless files (in the new branch) and added the .gitignore file. From now on, if you create some of the files indexed in .gitignore, they will not be synchronized with the repo. 

In case some files that do not belong to the repository appear in your commit, add corresponding file or folder name to the .gitignore (or ask someone to do it if you are not sure how). In GitHub Desktop, you can each time uncheck any changes that you do not want to commit, so use this feature on those files until the .gitignore file is updated.
